{% set name = "med-otm" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://files.salome-platform.org/Salome/medfile/med-{{ version }}.tar.gz
    sha256: a082b705d1aafe95d3a231d12c57f0b71df554c253e190acca8d26fc775fb1e6

build:
  number: 0

requirements:
  build:
    - cmake
    - curl
    - m2-base
    - m2w64-toolchain
    - m2w64-msmpi
    - hdf5-otm
  run:
    - m2w64-msmpi
    - hdf5-otm

about:
  home: https://www.salome-platform.org/user-section/about/med
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: COPYING
  summary: 'MED : interoperable format for data interchange between mesh based solvers.'
  description: |
    The purpose of the MED module is to provide a standard for storing and recovering computer data associated to numerical meshes and fields, and to facilitate the exchange between codes and solvers.
  doc_url: http://www.salome-platform.org/
  dev_url: https://git.salome-platform.org/gitweb/?p=modules/med.git;a=summary

extra:
  recipe-maintainers:
    - nicogodet
